owner: koj-co
repo: upptime
user-agent: KojBot
sites:
  - name: Kyu.co
    url: https://kyu.co
  - name: KyuPark.com
    url: https://kyupark.com
  - name: YejinLee.org
    url: https://yejinlee.org
  - name: SG JIRA
    url: https://jira.sophiagenetics.com
  - name: SG CHA
    url: https://cha.sophiagenetics.com/sga/status/infos.json
  - name: SG FRA
    url: https://fra.sophiagenetics.com/sga/status/infos.json
  - name: SG NL
    url: https://nl.sophiagenetics.com/sga/status/infos.json
  - name: SG TR
    url: https://tr.sophiagenetics.com/sga/status/infos.json   
  - name: SG US
    url: https://us.sophiagenetics.com/sga/status/infos.json
  - name: SG CA
    url: https://ca.sophiagenetics.com/sga/status/infos.json
  - name: SG BR
    url: https://br.sophiagenetics.com/sga/status/infos.json
  - name: SG OZ
    url: https://aus.sophiagenetics.com/sga/status/infos.json       
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - AnandChowdhary
status-website:
  cname: upptime.js.org
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
